### PR TITLE
[Feature] add steps name under step

### PR DESCRIPTION
**Pull request by juliooa**
Thanks for this useful library, I'm using it in one of my apps. I took the opportunity of _hacktoberfest_ to add a feature that I need on your library.

This PR adds the feature to include steps name under the circle step, like here:
screen shot 2018-10-15 at 9 43 02 pm

I also added the code for the sample app.

### CODE REVIEW

**Comment by imaNNeo** [comment]
Hi,
I appreciate your PR and i have to say that i joined hacktoberfest too :)
I have to commit some changes on your pr, and how i do this ?
I can merge it and do my changes on my repo right?
or can you give me access to push on your repository ( in a new branch ) and merge it to this branch and finally merge with Main Repo?

**Comment by juliooa** [comment]
@imaNNeoFighT I just add you as a collaborator, I hope that gives you the permissions.
If that doesn't work I can send this PR to another branch on your repo (develop for example), and then you can merge and do the changes, and when you are happy you can merge to master. Let me know what works for you. Thanks!

**Comment by imaNNeo** [comment]
ok let me check it, give me some times,
for now your PR counter increased for hacktoberfest because just creation time is important, and for sure i will accept it ASAP because this is a good feature,
Thanks, Regards!

**Comment by imaNNeo** [comment]
Hi dude, 
please accept my merge request on your repo, then i will merge it.
@juliooa

**Comment by juliooa** [comment]
@imaNNeoFighT done!

**Pull request merged**
